### ISSUE TITLE
Make the template into a `cls` file

### ISSUE THREAD

**Issue by salastro** [bshramin/uofa-eng-assignment#1]
Hello,

Having different components of the template itself inside the file in which problems are solved increases distractions and increases the possibility of breaking something by mistake. I think it would be better to separate the formatting from the actual content. [This template](https://github.com/artemmavrin/latex-homework) does something similar (and even explicitly mentions this decision). I hope it is possible to do such a thing to improve the quality of the template.

Thanks for the time.

**Comment by bshramin** [comment]
Hello, I completely agree with this. Are you willing to contribute and separate these two? I would appreciate it.

**Comment by salastro** [comment]
I have never tried doing this before, but I will try my best.

**Comment by bshramin** [comment]
Thank you.
